### ISSUE TITLE
Problem with params in route

### ISSUE THREAD

**Issue by TijlS** [ahkohd/express-php#3]
Hello

I wanted to use this for a project & I need to use params in my route, but when I search for them the browsers returns a '**Cannot GET**' error. The piece of code that sould sho the page is:
```php
$app->get('/GET/:module/', function($req, $res){
    $res->send('MODULE: ' . $req->params['module'] . print_r($req), array('Content-type' => 'text/html'));
});
```
But if I search /GET/:module/, I get '**Notice: Undefined index: module in C:\xampp\htdocs\mijnschool\API\index.php on line 24
Request Object ( [params] => Array ( ) ) MODULE: 1**'
Here is my configuration for espress-PHP:
```php
$app->set('basePath', '/API');
$app->set('view engine', 'default');
$app->set('views', 'pages/');
$app->set('env', 'development');
$app->set('error 401', '/401');
```
I hope someone can help me.

**Comment by MDominicG** [comment]
After a long time of working on this issue. I found a solution.

It's going to work if you are going to use params like so:
```
$app->get('/piese-auto/[:brandname]', function($req, $res){
    echo 'Brandname: '.$req->params['brandname'];
});
```

**Comment by Codetijl** [comment]
Thanks!

**Comment by ahkohd** [comment]
@Codetijl  I'm glad you found help.

@MDominicG thanks!

**Comment by ahkohd** [comment]
I'll update the docs.
